### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Alpha-Hashtag** [aplotor/expanse#47]
Hi, I don't know really anything about coding. I just want to install eternity. I watched the videos and tried clicking around the files after unzipping it. I can't figure out how to get to the very first screen you show in your Firebase setup guide video that you copy all the information from into Firebase. There is no .exe or .txt file so I'm unsure what to do. The link in your browser in the setup guide video just takes you to the Github page. does eternity even still work after the 3rd party app changes Reddit made? The post was archived, I'm just really confused and tried for an hour with no luck. I apologize for the shear level of noob this comment brings, any help is appreciated.

I did also try downloading expanse but still didn't know where to start, I don't really understand what cloning means with all the extra steps of docker etc... and the docker site says it has access to root security files which worries me because I have no idea what I'm doing and don't want to loose control of my PC. Thanks.

**Comment by aplotor** [comment]
- eternity shut down on 30-06-2023 due to the 01-07-2023 reddit api changes
- expanse is a selfhosted alternative to eternity, and is not aimed towards non-technical users to set up. id recommend either::
  - doing some research on the requirements and how to get them on your OS, after that the setup is very simple
  - getting a friend to host it for you
