### ISSUE TITLE
Problem when trying to start expanse

### ISSUE THREAD

**Issue by Anon-Anon443** [aplotor/expanse#51]
I've been successful before when starting expanse but as of late when running the starting line:

sh ./run.sh prod up

It started to give me this:

 app Pulling
 app Error manifest unknown
Error response from daemon: manifest unknown

I've logged in with a git token, I've updated the docker, tried to run the update command but it also gives a manifest unknown

I consulted with Gemini (cause chatgpt for pc is down) and came to the conclusion that the image cannot be found
I also tried to call for it directly

docker pull ghcr.io/jc9108/expanse:latest
Error response from daemon: manifest unknown

And that's what it gives me.

Any help is greatly appreciated! <3

**Comment by aplotor** [comment]
the image changed from `ghcr.io/jc9108/expanse` to `ghcr.io/aplotor/expanse` ~7 months ago in https://github.com/aplotor/expanse/commit/da454c58854531b1a20a088c8414541bfa76f7eb. if you update the app it should automatically update the image name in `compose.prod.yaml`

**Comment by aplotor** [comment]
if the update command doesnt work there may already be a mismatch between what the compose file expects and what the app container is on your machine, which may have been caused by calling docker commands outside of the provided `run.sh` script. i think the situation is that your existing container is already from the new image name but your `compose.prod.yaml` hasnt been updated. can you try manually updating the image name in line 21 of `compose.prod.yaml` to the new name, then see if the app starts from the provided `run.sh` script?

**Comment by aplotor** [comment]
if the update command doesnt work there may be a mismatch between what the compose file expects and what the app container is on your machine, which may have been caused by calling docker commands outside of the provided `run.sh` script. i think the situation is that your existing container is already from the new image name but your `compose.prod.yaml` hasnt been updated. can you try manually updating the image name in line 21 of `compose.prod.yaml` to the new name, then see if the app starts from the provided `run.sh` script?

**Comment by Anon-Anon443** [comment]
Yeah it seems that was the problem, so after I changed it manually it started to work. I don't what I did to have it not update automatically but after that it seems to work no problem. Thank you very much! <3
